[tools]
node = "24"
yarn = "3.8.7"
ruby = "ruby-3.4.8"

[env]
NODE_ENV = "development"

[tasks.fix-dev]
description = "Run when mise taks dev throws error"
run = """
rm -rf node_modules yarn.lock package-lock.json pnpm-lock.yaml
yarn cache clean
yarn install
"""

[tasks.dev]
description = "Start development server"
run = """
yarn dev &
bin/rails server
"""

[tasks.test]
description = "Run tests"
run = "yarn test"
